### ISSUE TITLE
总提示“WorkerManager - 39 - WARNING - dHydra运行目录下没有Worker文件夹”

### ISSUE THREAD

**Issue by ftong2010** [Emptyset110/dHydra#14]
很喜欢你的dHydra框架，很多QuantTrading的功能都可以轻松实现。这是我的初次试用，git clone之后发现无法启动，连接到Redis和MongoDB之后一直报错，错误信息“WorkerManager - 39 - WARNING - dHydra运行目录下没有Worker文件夹”

仔细检查一下发现在(dHydraRoot)/dHydra/core/util.py的第33行，应该是
``
worker_names.extend(os.listdir(os.getcwd()+"/dHydra/Worker"))
而不是
worker_names.extend(os.listdir(os.getcwd()+"/Worker"))

我自己修改了一下之后就好了。话说不知道是不是只有我有这个问题，这种启动不了的情况应该不会这么久都没人发现吧。。。。。。

**Comment by ftong2010** [comment]
哦，我的环境是Ubuntu 16.04 Desktop, Python 3.5，从远程桌面SSH进系统

**Comment by Emptyset110** [comment]
@ftong2010 谢谢关注。说实话这东西还很不完善。不过你提出的这一点呢，我最出的设计是os.getcwd()（运行环境当前目录）下面是自己需要建立一个Worker文件夹的，用来放置自己写的Worker，这个目录结构确实与./dHydra/目录的结构有相似性。在搜索的时候我是自己设置了这样的逻辑：先检测运行当前目录下的Worker文件夹内是否有这个Worker，没有的话再去dHydra目录下寻找，因为dHydra目录下的可能是我写的（可以理解为）“内置的”Worker，而开发者二次开发的时候只需要在当前目录下建立Worker，而不需要去修改dHydra/中的内容

**Comment by ftong2010** [comment]
你这个逻辑我在代码里一点也没看出来啊。。。。。。。。。。。。。。。。。。。。

麻烦问一下你这个from ctp.future中的ctp具体是哪一个包？我印象里CTP没有官方的Python包啊

**Comment by Emptyset110** [comment]
@ftong2010 前面那个逻辑你可以在dHydra.core.Functions里看到（就是实例化Worker和Vendor的函数）
ctp.future，你参考这里
https://github.com/lovelylain/pyctp/
按照他的README可以完成编译的。但是封装得不够好，我也在继续封装，现在（交易部分）大致能用，CTP行情是很容易调用的。pyctp里也有example

**Comment by ftong2010** [comment]
好的，谢谢啦，我再研究一下
