### ISSUE TITLE
实时抓取全部股票的逐笔交易数据，是否会被新浪屏蔽？

### ISSUE THREAD

**Issue by sisyphsu** [Emptyset110/dHydra#2]
正在使用这个工程的小伙伴们。

根据你们的经验，是否发生过访问量太大而被新浪屏蔽接口的情况？

我希望能够借助于这个工程，启动一个爬虫服务，从新浪抓取全部股票的实时逐笔交易数据，然后再拿着这些数据做后续的数据分析。

这样做会不会因为访问量太大，而被新浪屏蔽或者封禁账号呢？

**Comment by Emptyset110** [comment]
实时逐笔并不是用http抓取的呢，是websocket推送的，建立了连接以后就不存在再次建立连接的问题，所以也不存在访问频率高的问题呢。

另外，逐笔是可以通过一个http接口在盘后（盘中也可以）进行查询的，查看SinaVendor。实时的话肯定不可能用http抓。

另外新浪是封了阿里云的部分节点ip的。

**Comment by sisyphsu** [comment]
@Emptyset110  多谢你的解答~

如果采用websocket实时同步逐笔数据的话，是不是每支股票都需要一个websocket？

直接采用`SinaLevel2WSProducer`类的话，可以使用3000个股票代码作为`symbols`初始化参数吗？

如果采用上面做法的话，会不会由于websocket并发太多，而被新浪屏蔽。
比如说，新浪会不会限制每个账号的并发websocket数量？

因为我的最终需求是，实时同步全部股票的逐笔数据，非常担心并发量太大而被新浪屏蔽。。。

**Comment by Emptyset110** [comment]
@sulinixl 并发太高是否会被封这个问题，我只能说最终解释权属于新浪（全市场的行情和逐笔我同时获取过，过去没被封不代表将来不被封）。新浪是知道我们这样获取的，在购买l2的按钮下面有一行小字，说禁止恶意抓取数据，不保证云服务器上可用……另外L2的实时逐笔的可靠性我还没验证（比如是否有漏）

**Comment by sisyphsu** [comment]
@Emptyset110  明白啦~ 多谢哈~

**Comment by ldn0x7dc** [comment]
这两天新浪的反爬似乎加强了
爬取盘后逐笔的时候每秒超过两个访问就被屏蔽了
